# Generated by Django 5.0.7 on 2025-05-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(max_length=20)),
                ('donor_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('individual', 'Individual'), ('other', 'Other')], max_length=20)),
                ('food_type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pickup_address', models.TextField()),
                ('pickup_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('claimed', 'Claimed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donation')),
            ],
        ),
    ]
