# Generated by Django 5.0.7 on 2025-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_donationstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50)),
                ('org_type', models.CharField(choices=[('non_profit', 'Non-Profit'), ('charity', 'Charity'), ('community', 'Community Group')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_position', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('mission', models.TextField()),
                ('capacity', models.CharField(choices=[('small', 'Small (1-10 meals)'), ('medium', 'Medium (11-50 meals)'), ('large', 'Large (51+ meals)')], max_length=20)),
                ('has_transportation', models.BooleanField()),
                ('agreed_to_terms', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
